spring:
  application:
    name: altstore-source-manager
server:
  port: 8080
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  use-fqn: true
  # Load external OpenAPI YAML file
  springdoc:
    api-docs:
      custom-path: /openapi.yaml